CREATE OR REPLACE FUNCTION generate_team (a_team_count d_cnt, a_member_max d_cnt, a_psw TEXT, a_const_roles INTEGER[], a_random_roles INTEGER[], a_promo_code text DEFAULT NULL) RETURNS TEXT LANGUAGE 'plpgsql' AS
$_$
-- a_team_count: Количество автоматически создаваемых команд
-- a_member_max: Максимальное количество участников в команде
-- a_promo_code: Код сгенерированных команд
DECLARE
  v_team_id ws.d_id;
  v_account_id ws.d_id;
  v_member_max integer;
  v_promo_code text;
  v_t integer;
  v_a integer;
  v_const_rlen integer;
  v_random_rlen integer;
BEGIN
  v_const_rlen := array_length(a_const_roles, 1);
  v_random_rlen := array_length(a_random_roles, 1);
  IF a_member_max < (v_const_rlen + v_random_rlen) THEN
    RAISE EXCEPTION 'Member maximum must be more then %', (v_const_rlen + v_random_rlen);
  END IF;

  v_promo_code := COALESCE(a_promo_code, to_char(now(), 'YYMMDDHH24MI'));
  FOR v_t IN 1..a_team_count
  LOOP
    INSERT INTO wsd.team(name, status_id) VALUES (
      'Autogenerated team #' || v_t::text
      , acc.const_team_status_id_active()
    ) RETURNING id INTO v_team_id
    ;
    PERFORM cfg.prop_value_edit(acc.const_team_group_prop(), v_team_id::ws.d_id, 'object.promo'::cfg.d_prop_code, v_promo_code);
    v_member_max := v_const_rlen + floor(random() * (a_member_max - v_const_rlen + 1));
    FOR v_a IN 1..v_member_max
    LOOP
      INSERT INTO wsd.account(status_id, login, psw, name) VALUES (
        acc.const_status_id_active()
      , v_team_id::text ||'_acc_' || v_a::text
      , a_psw
      , 'Autogenerated account #' || v_a::text || ' / ' || v_team_id::text 
      ) RETURNING id INTO v_account_id
      ;
      INSERT INTO wsd.account_team(account_id, team_id, role_id) VALUES (
        v_account_id
      , v_team_id
      , CASE WHEN v_a <= v_const_rlen THEN a_const_roles[v_a]
             ELSE a_random_roles[floor(random() * v_random_rlen + 1)]
        END
      );
      PERFORM cfg.prop_value_edit(acc.const_account_group_prop(), v_account_id::ws.d_id, 'object.promo'::cfg.d_prop_code, v_promo_code);
    END LOOP;
  END LOOP;
  RETURN v_promo_code;
END;
$_$;
SELECT pg_c('f', 'generate_team', 'Автоматическая генерация команд');

/* ------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION drop_generated_team (a_promo_code text) RETURNS BOOL LANGUAGE 'sql' AS
$_$
  DELETE FROM wsd.account_team
    WHERE cfg.prop_value(acc.const_account_group_prop(), account_id, 'object.promo'::cfg.d_prop_code) = $1;
  DELETE FROM wsd.account
    WHERE cfg.prop_value(acc.const_account_group_prop(), id, 'object.promo'::cfg.d_prop_code) = $1;
  DELETE FROM wsd.team
    WHERE cfg.prop_value(acc.const_team_group_prop(), id, 'object.promo'::cfg.d_prop_code) = $1;
  SELECT TRUE;
$_$;
SELECT pg_c('f', 'drop_generated_team', 'Удаление автоматически созданных команд');

/* ------------------------------------------------------------------------- */

