# Generated by Makefile.PL
use Test;
use lib qw(. ./../../lib);
BEGIN { plan tests => 11 };
use PGWS; ok(1);
use PGWS::Daemon; ok(1);
use PGWS::Plugin; ok(1);
use PGWS::Frontend; ok(1);
use PGWS::Server; ok(1);
use PGWS::Meta; ok(1);
use PGWS::Plugin::System::Cache; ok(1);
use PGWS::Plugin::System::ACL; ok(1);
use PGWS::Frontend::CGI; ok(1);
#use PGWS::Frontend::Apache; ok(1);
use PGWS::Utils; ok(1);
use PGWS::ProcManager; ok(1);
